#!/bin/bash

echo "Building phantom2D..."

cd /home/janne/codes/flowblade/flowblade/flowblade-trunk/Flowblade/phantom2d

ant clean

#git clone https://github.com/jliljebl/phantom2D.git

ant copylocal

ant compile

ant jar



