#!/usr/bin/env python

"""
    Flowblade Movie Editor is a nonlinear video editor.
    Copyright 2012 Janne Liljeblad.

    This file is part of Flowblade Movie Editor <http://code.google.com/p/flowblade>.

    Flowblade Movie Editor is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Flowblade Movie Editor is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Flowblade Movie Editor.  If not, see <http://www.gnu.org/licenses/>.
"""

import os
import sys

print "MLT FRAME SERVER"
print "----------------"


modules_path = os.path.dirname(os.path.abspath(sys.argv[0])).rstrip("/phantom2d")

sys.path.insert(0, modules_path)
#sys.path.insert(0, modules_path + "/vieweditor")
#sys.path.insert(0, modules_path + "/tools")
sys.path.insert(0, modules_path + "/phantom2d")

# Get app.py module and set info which type of installation is running
try:
    import mltframeserver
except Exception, err:
    print "Failed to import mltframeserver"
    print "ERROR:", err
    print "Installation was assumed to be at:", modules_path
    sys.exit(1)
    


mltframeserver.main(modules_path)
