.TH FLOWBLADE 1 "SEPT 2010" Linux "User Manuals"
.SH NAME
flowblade \- Non-Linear Video Editor

.SH SYNOPSIS
.B flowblade 
[filename]

.SH DESCRIPTION
Flowblade is multitrack non-linear video editor.

.TP
.B More information
 Project Website: http://code.google.com/p/flowblade/
 User Website: http://code.google.com/p/flowblade/

.SH FILES
.I /home/your_user/.flowblade/
.RS
This folder stores preferences used by Flowblade.

.SH AUTHORS
Janne Liljeblad

