.TH FLOWBLADE 1 "SEPTEMBER 2015" Linux "User Manuals"
.SH NAME
flowblade \- Non-Linear Video Editor

.SH SYNOPSIS
.B flowblade
[\fIoptions\fR]
[\fIfile\fR]

.SH DESCRIPTION
Flowblade is a multitrack non-linear video editor released under GPL3 license.

From beginners to masters, Flowblade helps make your vision a reality of image and sound.

.TP
.B More information
 Project Website: https://github.com/jliljebl/flowblade
 User Website: https://github.com/jliljebl/flowblade
 Reference guide: https://jliljebl.github.io/flowblade/webhelp/help.html

.SH OPTIONS
.TP
.BR \-xdg
Use XDG specification and relocate program settings to
.I $XDG_CONFIG_DIR\fR/flowblade/ 

.SH FILES
.I /home/your_user/.flowblade/
.RS
This folder stores preferences used by Flowblade, unless
.B -xdg
flag is set.

.SH AUTHORS
Janne Liljeblad

