.TH FLOWBLADE 1 "JUNE 2014" Linux "User Manuals"
.SH NAME
flowblade \- Non-Linear Video Editor

.SH SYNOPSIS
.B flowblade 

.SH DESCRIPTION
Flowblade is multitrack non-linear video editor.

With Flowblade Movie Editor you can compose movies from video clips, 
audio clips and graphics files.

Clips can be cut at the desired frames, filters can be added to clips, 
and you can create multilayer composite images using compositor objects.

In Flowblade clips are usually automatically placed tightly after the previous 
clip - or between two existing clips - when they are inserted on the timeline.

Edits are fine tuned by trimming in and out points of clips, 
or by cutting and deleting parts of clips. 

.TP
.B More information
 Project Website: http://code.google.com/p/flowblade/
 User Website: http://code.google.com/p/flowblade/
 Reference guide: http://code.google.com/p/flowblade/wiki/FlowbladeReference

.SH FILES
.I /home/your_user/.flowblade/
.RS
This folder stores preferences used by Flowblade.

.SH AUTHORS
Janne Liljeblad

