#!/usr/bin/env python

import fileinput
import shutil

BOLD_O = "<b>"
BOLD_C = "</b>"
bold_is_open = True

LIST_ITEM = "  *"
LIST_ITEM_INNER = "    *"
LI_O = "<li>"
LI_C = "</li>"

H4_0 = "<h4>"
H4_C = "</h4>"

H3_0 = "<h3>"
H3_C = "</h3>"

H2_0 = "<h2>"
H2_C = "</h2>"

# -- funcs
def list_items(line):
    index = line.find(LIST_ITEM)
    if index == 0:
        line = line.replace(LIST_ITEM, LI_O)
        line = line + LI_C
    else:
        index = line.find(LIST_ITEM_INNER)
        if index == 0:
            line = line.replace(LIST_ITEM_INNER, LI_O)
            line = line + LI_C
        
    return line
 
def bolds(line):
    global bold_is_open
    index = 0
    while index != -1:
        index = line.find("*")
        if index != -1:
            if bold_is_open:
                tag = BOLD_O
                bold_is_open = False
            else:
                tag = BOLD_C
                bold_is_open = True

            line = line[:index + 1].replace('*', tag) + line[index + 1:]
    
    return line

def headers(line):
    if line[0:3] == "===":
        line =  line[:3].replace("===", H4_0) + line[3:]
        line = line.replace("===", H4_C)

    elif line[0:2] == "==":
        line =  line[:2].replace("==", H3_0) + line[2:]
        line = line.replace("==", H3_C)

    elif line[0:1] == "=":
        line =  line[:1].replace("=", H2_0) + line[1:]
        line = line.replace("=", H2_C)
        
    return line

  
# ---- main
orig_f = "/home/janne/codes/hg/flowblade/flowblade-trunk/Flowblade/res/help/help_orig.html"
f = "/home/janne/codes/hg/flowblade/flowblade-trunk/Flowblade/res/help/help.html"

print "haloo"

#shutil.copyfile(orig_f , f)

"""
for line in fileinput.input(f, inplace=True):
    line = line.rstrip("\n")
    line = list_items(line)
    line = line.strip()
    line = bolds(line)
    line = headers(line)
    print line
"""
