#!/usr/bin/python3

import sys
import os

import launchutils


def _get_arg_value(key_str):
    return launchutils.get_arg_value(key_str)


modules_path = launchutils.get_modules_path()
sys.path.insert(0, modules_path)

import processutils
processutils.update_sys_path(modules_path)

try:
    import gmicheadless
    launchutils.set_app_runtime_type(modules_path)
    
    session_id = _get_arg_value("session_id")
    parent_folder =  _get_arg_value("parent_folder")
    script = _get_arg_value("script")
    clip_path = _get_arg_value("clip_path")
    range_in = _get_arg_value("range_in")
    range_out = _get_arg_value("range_out")
    profile_desc_under_score = _get_arg_value("profile_desc")
    profile_desc = profile_desc_under_score.replace("_", " ") # We need to put underscores in profile names to get them here in one piece.
                                                              # Now we take underscores out to get correct MLT profile names.
    gmic_frame_offset = _get_arg_value("gmic_frame_offset")
except Exception as err:
    print ("Failed to import gmicheadless")
    print ("ERROR:", err)
    print ("Installation was assumed to be at:", modules_path)
    sys.exit(1)

gmicheadless.main(modules_path, session_id, parent_folder, script, clip_path, range_in, range_out, profile_desc, gmic_frame_offset)
