#!/usr/bin/python3

import sys
import os

import launchutils

modules_path = launchutils.get_modules_path()
sys.path.insert(0, modules_path)

import processutils
processutils.update_sys_path(modules_path)

try:
    import medialinker
    launchutils.set_app_runtime_type(modules_path)

except Exception as err:
    print ("Failed to import medialinker")
    print ("ERROR:", err)
    print ("Installation was assumed to be at:", modules_path)
    sys.exit(1)


medialinker.main(modules_path, sys.argv[1]) # sys.argv[1] is possibly a file path to project to be opened at startup
