#!/usr/bin/python3

import sys
import os

import launchutils


modules_path = launchutils.get_modules_path()
sys.path.insert(0, modules_path)

import processutils
processutils.update_sys_path(modules_path)

try:
    import gmic
    launchutils.set_app_runtime_type(modules_path)

except Exception as err:
    print ("Failed to import gmic")
    print ("ERROR:", err)
    print ("Installation was assumed to be at:", modules_path)
    sys.exit(1)


gmic.main(modules_path)
