#!/usr/bin/python3

import sys
import os

import launchutils


modules_path = launchutils.get_modules_path()
sys.path.insert(0, modules_path)

import processutils
processutils.update_sys_path(modules_path)

try:
    import projectmediaimport
    launchutils.set_app_runtime_type(modules_path)
except Exception:
    print ("Failed to import projectmediaimport")
    print ("ERROR:", err)
    print ("Installation was assumed to be at:", modules_path)
    sys.exit(1)


projectmediaimport.main(modules_path, sys.argv[1]) # sys.argv[1] is a file path to project that is the media import target
