#!/usr/bin/python3

import sys
import os

import launchutils

modules_path = modules_path = launchutils.get_modules_path()
sys.path.insert(0, modules_path)

import processutils
processutils.update_sys_path(modules_path)

import batchrendering

batchrendering.single_render_main(modules_path)
