#!/usr/bin/python3

import sys
import os

import launchutils


def _get_arg_value(key_str):
    return launchutils.get_arg_value(key_str)


modules_path = launchutils.get_modules_path()
sys.path.insert(0, modules_path)

import processutils
processutils.update_sys_path(modules_path)

try:
    import stabilizeheadless
    root_dir = modules_path.split("/")[1]

    session_id = _get_arg_value("session_id")
    parent_folder = _get_arg_value("parent_folder")
    write_file = _get_arg_value("write_file")
    clip_path = _get_arg_value("clip_path")
    accuracy = _get_arg_value("accuracy")
    shakiness = _get_arg_value("shakiness")
    smoothing = _get_arg_value("smoothing")
    zoom = _get_arg_value("zoom")
    profile_desc_under_score = _get_arg_value("profile_desc")
    profile_desc = profile_desc_under_score.replace("_", " ") # We need to put underscores in profile names to get them here in one piece.
                                                              # Now we take underscores out to get correct MLT profile names.
except Exception as err:
    print ("Failed to import statbilizeheadless")
    print ("ERROR:", err)
    print ("Installation was assumed to be at:", modules_path)
    sys.exit(1)

stabilizeheadless.main(modules_path, session_id, parent_folder, profile_desc, write_file, clip_path, accuracy, shakiness, smoothing, zoom)
