#!/usr/bin/python3

import sys
import os

import launchutils


def _get_arg_value(key_str):
    return launchutils.get_arg_value(key_str)


modules_path = launchutils.get_modules_path()
sys.path.insert(0, modules_path)

import processutils
processutils.update_sys_path(modules_path)

try:
    import trackingheadless

    session_id = _get_arg_value("session_id")
    parent_folder = _get_arg_value("parent_folder")
    write_file = _get_arg_value("write_file")
    data_file_path = _get_arg_value("data_file_path")
    clip_path = _get_arg_value("clip_path")
    clip_in = _get_arg_value("clip_in")
    clip_out = _get_arg_value("clip_out")
    step = _get_arg_value("step")
    algo = _get_arg_value("algo")
    rect_under_score = _get_arg_value("rect")
    rect = rect_under_score.replace("_", " ")
    profile_desc_under_score = _get_arg_value("profile_desc")
    profile_desc = profile_desc_under_score.replace("_", " ") # We need to put underscores in profile names to get them here in one piece.
                                                              # Now we take underscores out to get correct MLT profile names.
except Exception as err:
    print ("Failed to import trackingheadless")
    print ("ERROR:", err)
    print ("Installation was assumed to be at:", modules_path)
    sys.exit(1)

trackingheadless.main(modules_path, session_id, parent_folder, profile_desc, clip_path, clip_in, clip_out, write_file, data_file_path, step, algo, rect)




