#!/usr/bin/python3

import sys
import os

import launchutils


def _get_arg_value(key_str):
    return launchutils.get_arg_value(key_str)


modules_path = launchutils.get_modules_path()
sys.path.insert(0, modules_path)

import processutils
processutils.update_sys_path(modules_path)

try:
    import motionheadless
    launchutils.set_app_runtime_type(modules_path)

    session_id = _get_arg_value("session_id")
    parent_folder = _get_arg_value("parent_folder")
    speed = _get_arg_value("speed")
    write_file = _get_arg_value("write_file")
    encoding_option_index = _get_arg_value("encoding_option_index")
    quality_option_index = _get_arg_value("quality_option_index")
    source_path = _get_arg_value("source_path")
    render_full_range = _get_arg_value("render_full_range")
    start_frame = _get_arg_value("start_frame")
    end_frame = _get_arg_value("end_frame")
    profile_desc_under_score = _get_arg_value("profile_desc")
    profile_desc = profile_desc_under_score.replace("_", " ") # We need to put underscores in profile names to get them here in one piece.
                                                              # Now we take underscores out to get correct MLT profile names.
except Exception as err:
    print ("Failed to import mltxmlheadless")
    print ("ERROR:", err)
    print ("Installation was assumed to be at:", modules_path)
    sys.exit(1)

motionheadless.main(modules_path, session_id, parent_folder, speed, write_file, profile_desc, encoding_option_index, 
                    quality_option_index, source_path, render_full_range, start_frame, end_frame)




