#!/bin/bash

LANGUAGES=("cs" "fr" "es" "it" "de" "hu" "ru" "zh_CN" "pl" "zh_TW" "uk")

echo "Upgading all languages"

"./"create_pot

for LANG in "${LANGUAGES[@]}"
do
   :
   "./"update_language "${LANG}"
   "./"compile_language "${LANG}"
done
